# Generated by Django 3.2.8 on 2021-10-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='amountOfGames',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
