# Generated by Django 3.2.8 on 2021-10-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='amountOfPlayers',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='game',
            name='amountOfQuestions',
            field=models.IntegerField(default=10),
        ),
    ]
