# Generated by Django 3.2.8 on 2021-10-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_game_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000)),
                ('qtype', models.IntegerField(default=0)),
                ('a1', models.CharField(max_length=2000)),
                ('a2', models.CharField(max_length=2000)),
                ('a3', models.CharField(default=None, max_length=2000)),
                ('a4', models.CharField(default=None, max_length=2000)),
                ('nRight', models.IntegerField(default=0)),
            ],
        ),
    ]
